export type Offer = {
  id: string;
  name: string;
  logoText: string;
  logoIconPath?: string;
  affiliateUrl: string;
  goPath?: string;
  amountMinKzt?: number;
  maxAmountKzt: number;
  minTermDays: number;
  maxTermDays: number;
  rateTextRu: string;
  rateTextKk: string;
  aprTextRu?: string;
  aprTextKk?: string;
  gesvMax?: number;
  featuresRu: string[];
  featuresKk: string[];
  ctaTextRu?: string;
  ctaTextKk?: string;
  licenseDisclaimerRu?: string;
  licenseDisclaimerKk?: string;
  isPopular?: boolean;
  isTop?: boolean;
  priority: number;
  badgesRu?: string[];
  badgesKk?: string[];
};
